-- 000001_initial_schema.up.sql
-- Khớp chính xác schema từ database.sql (EF Core migrations).
-- Bao gồm cả ASP.NET Identity tables vì test scripts hiện có phụ thuộc vào chúng.

-- ASP.NET Identity tables ---------------------------------------------------

CREATE TABLE IF NOT EXISTS "AspNetRoles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "AspNetUsers" (
    "Id" uuid NOT NULL,
    "FullName" character varying(200) NOT NULL,
    "AvatarUrl" character varying(500) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "Role" integer NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId")
        REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId")
        REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

-- Domain tables -------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "Addresses" (
    "Id" uuid NOT NULL,
    "FullName" text NOT NULL,
    "Phone" text NOT NULL,
    "Street" text NOT NULL,
    "Ward" text NOT NULL,
    "District" text NOT NULL,
    "City" text NOT NULL,
    "IsDefault" boolean NOT NULL,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_Addresses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Addresses_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Shops" (
    "Id" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Slug" character varying(200) NOT NULL,
    "Description" text NOT NULL,
    "LogoUrl" text NOT NULL,
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "OwnerId" uuid NOT NULL,
    CONSTRAINT "PK_Shops" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Shops_AspNetUsers_OwnerId" FOREIGN KEY ("OwnerId")
        REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "Categories" (
    "Id" uuid NOT NULL,
    "Name" character varying(150) NOT NULL,
    "Slug" character varying(150) NOT NULL,
    "Description" text NOT NULL,
    "ParentId" uuid,
    "OwnerShopId" uuid,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Categories_Categories_ParentId" FOREIGN KEY ("ParentId")
        REFERENCES "Categories" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "Products" (
    "Id" uuid NOT NULL,
    "Name" character varying(300) NOT NULL,
    "Slug" character varying(300) NOT NULL,
    "Description" text NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "SalePrice" numeric(18,2),
    "StockQuantity" integer NOT NULL,
    "Sku" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CategoryId" uuid,
    "ShopId" uuid NOT NULL,
    "WarrantyMonths" integer DEFAULT 0 NOT NULL,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Products_Shops_ShopId" FOREIGN KEY ("ShopId")
        REFERENCES "Shops" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId")
        REFERENCES "Categories" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "ProductImages" (
    "Id" uuid NOT NULL,
    "Url" character varying(500) NOT NULL,
    "AltText" text NOT NULL,
    "IsPrimary" boolean NOT NULL,
    "DisplayOrder" integer NOT NULL,
    "ProductId" uuid NOT NULL,
    CONSTRAINT "PK_ProductImages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProductImages_Products_ProductId" FOREIGN KEY ("ProductId")
        REFERENCES "Products" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Orders" (
    "Id" uuid NOT NULL,
    "OrderCode" character varying(50) NOT NULL,
    "Status" integer NOT NULL,
    "TotalAmount" numeric(18,2) NOT NULL,
    "ShippingFee" numeric(18,2) NOT NULL,
    "Note" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "PaidAt" timestamp with time zone,
    "UserId" uuid NOT NULL,
    "AddressId" uuid NOT NULL,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Orders_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Orders_Addresses_AddressId" FOREIGN KEY ("AddressId")
        REFERENCES "Addresses" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "OrderDetails" (
    "Id" uuid NOT NULL,
    "Quantity" integer NOT NULL,
    "UnitPrice" numeric(18,2) NOT NULL,
    "TotalPrice" numeric(18,2) NOT NULL,
    "OrderId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    CONSTRAINT "PK_OrderDetails" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrderDetails_Orders_OrderId" FOREIGN KEY ("OrderId")
        REFERENCES "Orders" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OrderDetails_Products_ProductId" FOREIGN KEY ("ProductId")
        REFERENCES "Products" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "Reviews" (
    "Id" uuid NOT NULL,
    "Rating" integer NOT NULL,
    "Comment" character varying(1000) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ProductId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reviews_Products_ProductId" FOREIGN KEY ("ProductId")
        REFERENCES "Products" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Reviews_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "CartItems" (
    "Id" uuid NOT NULL,
    "Quantity" integer NOT NULL,
    "UserId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    CONSTRAINT "PK_CartItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CartItems_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CartItems_Products_ProductId" FOREIGN KEY ("ProductId")
        REFERENCES "Products" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "RefreshTokens" (
    "Id" uuid NOT NULL,
    "Token" character varying(500) NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsRevoked" boolean NOT NULL,
    "IsUsed" boolean NOT NULL,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RefreshTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Conversations" (
    "Id" uuid NOT NULL,
    "BuyerId" uuid NOT NULL,
    "ShopId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastMessageAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Conversations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Conversations_AspNetUsers_BuyerId" FOREIGN KEY ("BuyerId")
        REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Conversations_Shops_ShopId" FOREIGN KEY ("ShopId")
        REFERENCES "Shops" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "ChatMessages" (
    "Id" uuid NOT NULL,
    "ConversationId" uuid NOT NULL,
    "SenderId" uuid NOT NULL,
    "Content" character varying(2000) NOT NULL,
    "IsRead" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ChatMessages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ChatMessages_Conversations_ConversationId" FOREIGN KEY ("ConversationId")
        REFERENCES "Conversations" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ChatMessages_AspNetUsers_SenderId" FOREIGN KEY ("SenderId")
        REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "WarrantyClaims" (
    "Id" uuid NOT NULL,
    "ClaimCode" character varying(50) NOT NULL,
    "Description" character varying(2000) NOT NULL,
    "ImageUrl" character varying(500) NOT NULL,
    "Status" integer NOT NULL,
    "Resolution" integer NOT NULL,
    "ResolutionNote" character varying(1000) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "ResolvedAt" timestamp with time zone,
    "OrderDetailId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "ShopId" uuid NOT NULL,
    CONSTRAINT "PK_WarrantyClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WarrantyClaims_OrderDetails_OrderDetailId" FOREIGN KEY ("OrderDetailId")
        REFERENCES "OrderDetails" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_WarrantyClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WarrantyClaims_Products_ProductId" FOREIGN KEY ("ProductId")
        REFERENCES "Products" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WarrantyClaims_Shops_ShopId" FOREIGN KEY ("ShopId")
        REFERENCES "Shops" ("Id") ON DELETE RESTRICT
);

-- EF Migrations History (giữ lại để tương thích nếu cần) ---------
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- Indexes (khớp chính xác schema C#) ----------------------------------------

CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
CREATE INDEX IF NOT EXISTS "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
CREATE INDEX IF NOT EXISTS "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
CREATE INDEX IF NOT EXISTS "IX_Addresses_UserId" ON "Addresses" ("UserId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Shops_Slug" ON "Shops" ("Slug");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Shops_OwnerId" ON "Shops" ("OwnerId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Categories_Slug" ON "Categories" ("Slug");
CREATE INDEX IF NOT EXISTS "IX_Categories_ParentId" ON "Categories" ("ParentId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Products_Slug" ON "Products" ("Slug");
CREATE INDEX IF NOT EXISTS "IX_Products_ShopId" ON "Products" ("ShopId");
CREATE INDEX IF NOT EXISTS "IX_Products_CategoryId" ON "Products" ("CategoryId");
CREATE INDEX IF NOT EXISTS "IX_ProductImages_ProductId" ON "ProductImages" ("ProductId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Orders_OrderCode" ON "Orders" ("OrderCode");
CREATE INDEX IF NOT EXISTS "IX_Orders_UserId" ON "Orders" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_Orders_AddressId" ON "Orders" ("AddressId");
CREATE INDEX IF NOT EXISTS "IX_OrderDetails_OrderId" ON "OrderDetails" ("OrderId");
CREATE INDEX IF NOT EXISTS "IX_OrderDetails_ProductId" ON "OrderDetails" ("ProductId");
CREATE INDEX IF NOT EXISTS "IX_Reviews_ProductId" ON "Reviews" ("ProductId");
CREATE INDEX IF NOT EXISTS "IX_Reviews_UserId" ON "Reviews" ("UserId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_CartItems_UserId_ProductId" ON "CartItems" ("UserId", "ProductId");
CREATE INDEX IF NOT EXISTS "IX_CartItems_ProductId" ON "CartItems" ("ProductId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_RefreshTokens_Token" ON "RefreshTokens" ("Token");
CREATE INDEX IF NOT EXISTS "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Conversations_BuyerId_ShopId" ON "Conversations" ("BuyerId", "ShopId");
CREATE INDEX IF NOT EXISTS "IX_Conversations_ShopId" ON "Conversations" ("ShopId");
CREATE INDEX IF NOT EXISTS "IX_ChatMessages_ConversationId_CreatedAt" ON "ChatMessages" ("ConversationId", "CreatedAt");
CREATE INDEX IF NOT EXISTS "IX_ChatMessages_SenderId" ON "ChatMessages" ("SenderId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_WarrantyClaims_ClaimCode" ON "WarrantyClaims" ("ClaimCode");
CREATE INDEX IF NOT EXISTS "IX_WarrantyClaims_OrderDetailId" ON "WarrantyClaims" ("OrderDetailId");
CREATE INDEX IF NOT EXISTS "IX_WarrantyClaims_UserId" ON "WarrantyClaims" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_WarrantyClaims_ProductId" ON "WarrantyClaims" ("ProductId");
CREATE INDEX IF NOT EXISTS "IX_WarrantyClaims_ShopId" ON "WarrantyClaims" ("ShopId");
